-- settings
require("settings.colorschemes")
require("settings.keymaps")
require("settings.options")
require("settings.plugins")
require("settings.impatient")
-- plugins
require("configs.alpha")
require("configs.autocommands")
require("configs.autopairs")
require("configs.autosave")
require("configs.better_escape")
-- require("configs.bufferline")
require("configs.cmp")
require("configs.colorizer")
require("configs.comments")
require("configs.copilot")
require("configs.cybu")
require("configs.dap")
require("configs.dressing")
require("configs.eyeliner")
require("configs.fidget")
require("configs.filetype")
require("configs.gitlinker")
require("configs.gitsigns")
require("configs.harpoon")
require("configs.hop")
require("configs.icons")
require("configs.illuminate")
require("configs.indentline")
-- require("configs.inlay-hints") TODO: make this work properly
require("configs.jabs")
require("configs.jaq")
require("configs.lab")
-- require("configs.lsp-inlayhints") TODO: make this work properly
require("configs.lualine")
require("configs.matchup")
require("configs.navic")
require("configs.neoscroll")
require("configs.notify")
require("configs.numb")
require("configs.nvim-tree")
require("configs.presence")
require("configs.project")
require("configs.quickscope")
require("configs.registers")
require("configs.renamer")
require("configs.scope")
require("configs.spectre")
require("configs.surround")
require("configs.symbol-outline")
require("configs.tabout")
require("configs.telescope")
require("configs.todo-comments")
require("configs.toggleterm")
require("configs.treesitter")
require("configs.trouble")
require("configs.true-zen")
require("configs.ts-context")
require("configs.vim-slash")
require("configs.webdev-icons")
require("configs.whichkey")
-- LSP
require("lsp")
