require("settings.options")
require("settings.plugins")
require("settings.colorschemes")
require("settings.cmp")
require("settings.lsp")
require("settings.keymaps")
require("settings.telescope")
require("settings.autopairs")
require("settings.gitsigns")
require("settings.nvim-tree")
require("settings.lualine")
require("settings.presence")
require("settings.bufferline")
require("settings.comments")
require("settings.autosave")
-- require("settings.treesitter")
-- require("settings.toggleterm")
