	-- settings
require("settings.colorschemes")
require("settings.keymaps")
require("settings.options")
require("settings.plugins")
require("settings.impatient")
-- plugins
require("configs.alpha")
require("configs.autocommands")
require("configs.autopairs")
require("configs.autosave")
require("configs.better_escape")
require("configs.bufferline")
require("configs.cmp")
require("configs.colorizer")
require("configs.comments")
require("configs.dap")
require("configs.filetype")
require("configs.gitsigns")
require("configs.icons")
require("configs.illuminate")
require("configs.indentline")
require("configs.lualine")
require("configs.neoscroll")
require("configs.nvim-tree")
require("configs.presence")
require("configs.project")
require("configs.symbol-outline")
require("configs.telescope")
require("configs.toggleterm")
require("configs.treesitter")
require("configs.trouble")
require("configs.webdev-icons")
require("configs.whichkey")
-- LSP
require("lsp")
